name: Build and Deploy Angular App to Azure Static Web App

on:
  push:
    branches:
      - main 
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Angular App

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --configuration=production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0FFD0D203 }}
          action: "upload"
          app_location: "dist/invites"
          output_location: ""
