name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy pre-built Angular app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy pre-built dist/invites
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0FFD0D203 }}
          action: "upload"
          app_location: "dist/invites/browser" #  Azure to deploy from this folder
          output_location: ""          #  Azure: "No build step"
